---
- name: Set up volume list
  ansible.builtin.set_fact:
    watchtower_volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock

- name: Check if file '/root/.docker/config.json' exists.
  ansible.builtin.stat:
    path: "/root/.docker/config.json"
  register: docker_config_file

- name: Set up volume list
  ansible.builtin.set_fact:
    watchtower_volumes: "{{ watchtower_volumes + ['/root/.docker/config.json:/config.json'] }}"
  when: docker_config_file.stat.exists

- name: Append notification_env to env's
  ansible.builtin.set_fact:
    watchtower_env: "{{ watchtower_env | combine(notification_env) }}"

# copy configuration
- name: Generate and copy env file
  ansible.builtin.template:
    src: "watchtower_env.j2"
    dest: "{{ docker_watchtower_path }}/.env"
    owner: "{{ docker_watchtower_dynamic_user }}"
    group: "{{ docker_watchtower_dynamic_group }}"
    mode: "0644"
  diff: true

- name: Start Watchtower
  become: true
  community.docker.docker_container:
    name: watchtower
    image: nickfedor/watchtower
    userns_mode: "host"
    comparisons:
      "*": strict
    pull: true
    state: started
    restart_policy: unless-stopped
    volumes: "{{ watchtower_volumes }}"
    env_file: "{{ docker_watchtower_path }}/.env"
